# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#from dash import Ui_dashboard_window
from main import process_authen
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtSql import QSqlTableModel, QSqlDatabase
from PyQt5.QtWidgets import QTableView, QMessageBox
from PyQt5.QtCore import Qt

class Ui_dashboard_window(object):
    def setupUi(self, dashboard_window):
        dashboard_window.setObjectName("dashboard_window")
        dashboard_window.resize(882, 494)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dashboard_window.sizePolicy().hasHeightForWidth())
        dashboard_window.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(dashboard_window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 121, 16))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(760, 10, 111, 23))
        self.pushButton.setObjectName("pushButton")
        # set up model
        self.user_model = QSqlTableModel()
        self.user_model.setTable("user")
        self.user_model.setEditStrategy(QSqlTableModel.OnFieldChange)
        self.user_model.setHeaderData(0, Qt.Horizontal, "ID")
        self.user_model.setHeaderData(1, Qt.Horizontal, "Username")
        self.user_model.setHeaderData(2, Qt.Horizontal, "Password")
        self.user_model.setHeaderData(3, Qt.Horizontal, "2 FA code")
        self.user_model.setHeaderData(4, Qt.Horizontal, "IP address")
        self.user_model.setHeaderData(5, Qt.Horizontal, "Status")
        self.user_model.select()
        # set up view
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 40, 861, 411))
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setStretchLastSection(True)
        #self.tableView.horizontalHeader().setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeMode.Stretch)
        self.tableView.verticalHeader().setVisible(False)
        self.tableView.setModel(self.user_model)
        self.tableView.resizeColumnsToContents()
        self.tableView.verticalHeader().setHighlightSections(True)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(680, 10, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        dashboard_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(dashboard_window)
        self.statusbar.setObjectName("statusbar")
        dashboard_window.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(dashboard_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 882, 21))
        self.menubar.setObjectName("menubar")
        dashboard_window.setMenuBar(self.menubar)

        self.retranslateUi(dashboard_window)
        QtCore.QMetaObject.connectSlotsByName(dashboard_window)
    
        def open_firefox(self, ):
                ####### tobe coded######
                open_firefox_1(self, self.username, self.password)
        
        self.pushButton_2.clicked.connect(open_firefox)

    def retranslateUi(self, dashboard_window):
        _translate = QtCore.QCoreApplication.translate
        dashboard_window.setWindowTitle(_translate("dashboard_window", "Dashboard"))
        self.label.setText(_translate("dashboard_window", "Account list"))
        self.pushButton.setText(_translate("dashboard_window", "Connect to server"))
        self.pushButton_2.setText(_translate("dashboard_window", "Open Firefox"))

class Ui_login_window(object):
    def dash(self):
        self.window2 = QtWidgets.QMainWindow()
        ui = Ui_dashboard_window()
        ui.setupUi(self.window2)
        self.window2.show()

    def setupUi(self, login_window):
        login_window.setObjectName("login_window")
        login_window.resize(272, 258)
        self.centralwidget = QtWidgets.QWidget(login_window)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 80, 221, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 140, 221, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 50, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 81, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 180, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 221, 16))
        self.label_3.setObjectName("label_3")
        login_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(login_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 272, 21))
        self.menubar.setObjectName("menubar")
        login_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(login_window)
        self.statusbar.setObjectName("statusbar")
        login_window.setStatusBar(self.statusbar)

        self.retranslateUi(login_window)
        QtCore.QMetaObject.connectSlotsByName(login_window)

        def push_login():
            #print(self.lineEdit.text)
            process_authen(self, self.lineEdit.text(), self.lineEdit_2.text(), login_window)

        self.pushButton.clicked.connect(push_login)

    def retranslateUi(self, login_window):
        _translate = QtCore.QCoreApplication.translate
        login_window.setWindowTitle(_translate("login_window", "Log In"))
        self.label.setText(_translate("login_window", "Username"))
        self.label_2.setText(_translate("login_window", "Password"))
        self.pushButton.setText(_translate("login_window", "Login"))
        self.label_3.setText(_translate("login_window", "Hello! Please login to Tool!"))

def process_authen(self, user, password, login_window):
    if user == "admin" and password == "admin":
        print("correct!")
        self.dash()
        login_window.close()
    else:
        print("incorrect!")
        QMessageBox.critical(
            None,
            None,
            "Login Fail!",
            QMessageBox.Ok
        )
    ### Process connect to BE web here ###

def createConnection():
    con = QSqlDatabase.addDatabase("QSQLITE")
    con.setDatabaseName("user.sqlite")
    if not con.open():
        QMessageBox.critical(
            None,
            "QTableView Example - Error!",
            "Database Error: %s" % con.lastError().databaseText(),
        )
        return False
    return True

def open_firefox_1(self, username, password):
    pass
####### tobe coded######

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    if not createConnection():
        sys.exit(1)
    login_window = QtWidgets.QMainWindow()
    ui = Ui_login_window()
    ui.setupUi(login_window)
    login_window.show()
    sys.exit(app.exec_())
